import React from 'react';
import { 
  X, 
  FolderOpen, 
  CheckCircle2, 
  AlertTriangle, 
  Cpu,
  Layers,
  ShieldCheck,
  RotateCcw
} from 'lucide-react';
import { FileCandidate } from '../types/candidate';
import { formatBytes } from '../utils/formatters';
import { AIBadge, CategoryBadge, ConfidenceBadge, LockBadge, RiskBadge } from './Badges';
import { api } from '../services/api';

interface CandidateDetailDrawerProps {
  candidate: FileCandidate | null;
  onClose: () => void;
  isSelected: boolean;
  onToggleSelect: (candidate: FileCandidate) => void;
  onAnalyzeAI?: (candidate: FileCandidate) => void;
  isAnalyzing?: boolean;
}

export const CandidateDetailDrawer: React.FC<CandidateDetailDrawerProps> = ({
  candidate,
  onClose,
  isSelected,
  onToggleSelect,
  onAnalyzeAI,
  isAnalyzing = false,
}) => {
  if (!candidate) return null;

  const handleOpenExplorer = () => {
    api.openInExplorer(candidate.path);
  };

  return (
    <div className="fixed inset-y-0 right-0 w-full max-w-xl bg-[#080808] border-l border-[#1a1a1a] shadow-2xl z-50 flex flex-col transition-transform duration-200">
      {/* Header */}
      <div className="p-5 border-b border-[#161616] flex items-center justify-between bg-[#0b0b0b]">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-md bg-[#141414] border border-[#222222]">
            <Layers className="w-4 h-4 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-[#f5f5f5] tracking-tight truncate max-w-sm" title={candidate.name}>
              {candidate.name}
            </h2>
            <p className="text-[11px] text-[#71717a] font-mono truncate max-w-sm">
              {formatBytes(candidate.sizeBytes)} {candidate.itemCount ? `• ${candidate.itemCount.toLocaleString()} items` : ''}
            </p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="p-1.5 rounded-md text-[#71717a] hover:text-[#f5f5f5] hover:bg-[#161616] transition-colors outline-none"
          title="Close details"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Body Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {/* Quick Metadata Pill Grid */}
        <div className="flex flex-wrap items-center gap-2">
          <RiskBadge risk={candidate.riskLevel} />
          <CategoryBadge category={candidate.category} />
          <ConfidenceBadge confidence={candidate.confidence} />
          <LockBadge inUse={candidate.inUse} processName={candidate.owningProcess} />
          <AIBadge provider={candidate.aiProvider} />
        </div>

        {/* Location Path Box */}
        <div className="space-y-1.5">
          <label className="text-[10px] font-mono uppercase tracking-wider text-[#71717a]">
            Filesystem Path
          </label>
          <div className="p-3 rounded-lg bg-[#050505] border border-[#1a1a1a] flex items-center justify-between gap-3">
            <span className="text-xs font-mono text-[#a1a1aa] break-all select-all">
              {candidate.path}
            </span>
            <button
              onClick={handleOpenExplorer}
              className="flex-shrink-0 p-1.5 rounded text-[#71717a] hover:text-[#f5f5f5] hover:bg-[#141414] transition-colors outline-none"
              title="Open folder in Windows File Explorer"
            >
              <FolderOpen className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Explainability Cards */}
        <div className="space-y-3">
          <label className="text-[10px] font-mono uppercase tracking-wider text-[#71717a] flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-indigo-400" />
            Explainability & Deletion Safety
          </label>

          {/* 1. What exactly is this? */}
          <div className="p-3.5 rounded-lg bg-[#0c0c0c] border border-[#181818] space-y-1.5">
            <span className="text-xs font-medium text-[#d4d4d8] flex items-center gap-1.5">
              1. What is this item?
            </span>
            <p className="text-xs text-[#a1a1aa] leading-relaxed">
              {candidate.explanation}
            </p>
          </div>

          {/* 2. Why is it on my computer? */}
          <div className="p-3.5 rounded-lg bg-[#0c0c0c] border border-[#181818] space-y-1.5">
            <span className="text-xs font-medium text-[#d4d4d8] flex items-center gap-1.5">
              2. Why is it on my computer?
            </span>
            <p className="text-xs text-[#a1a1aa] leading-relaxed">
              {candidate.relatedApplication 
                ? `Generated by ${candidate.relatedApplication} during normal operations, builds, or exports.` 
                : 'Accumulated by installed system tools, developer workflows, or background caches.'}
            </p>
          </div>

          {/* 3. Is anything currently using it? */}
          <div className="p-3.5 rounded-lg bg-[#0c0c0c] border border-[#181818] space-y-1.5">
            <span className="text-xs font-medium text-[#d4d4d8] flex items-center gap-1.5">
              3. Is anything currently using it?
            </span>
            <div className="flex items-center gap-2">
              {candidate.inUse ? (
                <div className="flex items-center gap-2 text-amber-400 text-xs">
                  <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>
                    Currently locked {candidate.owningProcess ? `by ${candidate.owningProcess}` : 'by an active process'}.
                  </span>
                </div>
              ) : (
                <div className="flex items-center gap-2 text-emerald-400 text-xs">
                  <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0" />
                  <span>No active Windows file locks detected.</span>
                </div>
              )}
            </div>
          </div>

          {/* 4. What happens if I remove it? */}
          <div className="p-3.5 rounded-lg bg-[#0c0c0c] border border-[#181818] space-y-1.5">
            <span className="text-xs font-medium text-[#d4d4d8] flex items-center gap-1.5">
              <RotateCcw className="w-3.5 h-3.5 text-amber-400" />
              4. What happens if removed?
            </span>
            <p className="text-xs text-[#a1a1aa] leading-relaxed">
              {candidate.deleteEffect}
            </p>
          </div>
        </div>

        {/* Evidence Checklist */}
        {candidate.evidence && candidate.evidence.length > 0 && (
          <div className="space-y-2">
            <label className="text-[10px] font-mono uppercase tracking-wider text-[#71717a]">
              Verification Evidence
            </label>
            <div className="p-3 rounded-lg bg-[#0c0c0c] border border-[#181818] space-y-2">
              {candidate.evidence.map((item, idx) => (
                <div key={idx} className="flex items-start gap-2 text-xs text-[#a1a1aa]">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 mt-0.5 flex-shrink-0" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Footer Actions */}
      <div className="p-4 border-t border-[#161616] bg-[#0a0a0a] flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          {onAnalyzeAI && (
            <button
              onClick={() => onAnalyzeAI(candidate)}
              disabled={isAnalyzing}
              className="inline-flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium bg-[#141414] text-[#e4e4e7] border border-[#242424] hover:bg-[#1a1a1a] transition-colors disabled:opacity-50 outline-none"
            >
              <Cpu className="w-3.5 h-3.5 text-indigo-400" />
              {isAnalyzing ? 'Reasoning...' : 'Deep AI Reasoning'}
            </button>
          )}
        </div>

        <button
          onClick={() => onToggleSelect(candidate)}
          className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-colors outline-none ${
            isSelected
              ? 'bg-rose-950/40 text-rose-300 border border-rose-800/40 hover:bg-rose-900/50'
              : 'bg-indigo-600 text-white hover:bg-indigo-500 shadow-sm'
          }`}
        >
          {isSelected ? 'Deselect Candidate' : 'Select for Cleanup'}
        </button>
      </div>
    </div>
  );
};
